version: '3.1'

services:

  lgin-api:
    container_name: lgin-api
    build: lgin-api/
    stdin_open: true
    tty: true
    volumes:
     - lgin-sqlite:/app/db

  sp-lgin-commserver:
    container_name: sp-lgin-commserver
    build: sp-lgin-commserver/
    stdin_open: true
    tty: true
    volumes:
      - sp-lgin-save:/app/save
    depends_on: 
      - lgin-api

  lgin-sp-gui:
    container_name: lgin-sp-gui
    build: lgin-sp-gui/
    stdin_open: true
    tty: true
    depends_on:
      - lgin-api
      - sp-lgin-commserver

  sp-lgin-proxy:
    container_name: sp-lgin-proxy
    build: sp-lgin-proxy/
    ports:
        - 80:80
        - 443:443
    depends_on:
      - sp-lgin-commserver
      - lgin-sp-gui
      - lgin-api

volumes:
  lgin-sqlite:
  sp-lgin-save:
   