version: '3.1'

services:
  lgin-sqlserver:
    container_name: lgin-sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mWe92cBCMA5M
      - MSSQL_DATA_DIR=/var/opt/sqlserver/data
      - MSSQL_LOG_DIR=/var/opt/sqlserver/log
      - MSSQL_BACKUP_DIR=/var/opt/sqlserver/backup
    volumes: 
          - lgin-sqlsystem:/var/opt/mssql/
          - lgin-sqldata:/var/opt/sqlserver/data
          - lgin-sqllog:/var/opt/sqlserver/log
          - lgin-sqlbackup:/var/opt/sqlserver/backup

  lgin-api:
    container_name: lgin-api
    build: lgin-api/
    stdin_open: true
    tty: true
    depends_on:
      - lgin-sqlserver

  sp-lgin-commserver:
    container_name: sp-lgin-commserver
    build: sp-lgin-commserver/
    stdin_open: true
    tty: true
    volumes:
      - sp-lgin-save:/app/save
    depends_on: 
      - lgin-api

  lgin-sp-gui:
    container_name: lgin-sp-gui
    build: lgin-sp-gui/
    stdin_open: true
    tty: true
    depends_on:
      - lgin-api
      - sp-lgin-commserver

  sp-lgin-proxy:
    container_name: sp-lgin-proxy
    build: sp-lgin-proxy/
    ports:
        - 80:80
        - 443:443
    depends_on:
      - sp-lgin-commserver
      - lgin-sp-gui
      - lgin-api

volumes:
  lgin-sqlsystem:
  lgin-sqldata:
  lgin-sqllog:
  lgin-sqlbackup:
  sp-lgin-save:
   